# Generated by Django 4.1 on 2022-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('phone_name', models.CharField(max_length=50)),
                ('phone_colour', models.CharField(max_length=10, null=True)),
                ('phone_images', models.ImageField(blank=True, upload_to='phone_image')),
                ('storage', models.IntegerField()),
            ],
        ),
    ]
