# Generated by Django 4.1 on 2022-08-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phones',
            new_name='Smart_phone',
        ),
    ]
