# Generated by Django 4.1 on 2022-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_rename_phones_smart_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_phone',
            name='avalablity',
            field=models.BooleanField(default=True),
        ),
    ]
