# Generated by Django 4.1 on 2022-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_smart_phone_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='images',
            field=models.ImageField(blank=True, upload_to='phone_image'),
        ),
    ]
