# Generated by Django 4.1 on 2022-09-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_smart_phone_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart_watch',
            old_name='size',
            new_name='display_size',
        ),
    ]
