# Generated by Django 4.1 on 2022-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_smart_watches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smart_watches',
            new_name='Smart_watche',
        ),
    ]
