# Generated by Django 4.1 on 2022-09-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_rename_size_smart_watch_display_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart_watch',
            old_name='display_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='tabs',
            old_name='size',
            new_name='display_size',
        ),
    ]
