# Generated by Django 4.1 on 2022-09-22 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_rename_display_size_smart_watch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 38, 27, 354468)),
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 38, 27, 354468)),
        ),
        migrations.AddField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 38, 27, 354468)),
        ),
    ]
