# Generated by Django 4.1 on 2022-08-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_rename_smart_watches_smart_watche'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smart_watche',
            new_name='Smart_watch',
        ),
    ]
