# Generated by Django 4.1 on 2022-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_smart_phone_phone_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('brand', models.CharField(max_length=20)),
                ('tab_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tablet_colour', models.CharField(max_length=10, null=True)),
                ('tablet_images', models.ImageField(blank=True, upload_to='tablet_image')),
                ('size', models.IntegerField()),
                ('avalablity', models.BooleanField(default=True)),
                ('instock_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='smart_phone',
            options={'verbose_name_plural': 'Smart Phones'},
        ),
        migrations.RemoveField(
            model_name='smart_watch',
            name='name',
        ),
        migrations.AddField(
            model_name='smart_phone',
            name='instock_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='instock_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='phone_images',
            field=models.ImageField(blank=True, upload_to='phone_image'),
        ),
    ]
