# Generated by Django 4.1 on 2022-09-25 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_smart_phone_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_phoneinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(blank=True, default=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 28, 42, 385973)),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 28, 42, 385973)),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 28, 42, 385973)),
        ),
    ]
