# Generated by Django 4.1 on 2022-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_remove_smart_watch_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smart_watch',
            name='id',
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='brand',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='watch_name',
            field=models.CharField(default='name', max_length=30, primary_key=True, serialize=False),
        ),
    ]
