# Generated by Django 4.1 on 2022-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_remove_smart_watch_id_smart_watch_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_watch',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='watch_name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
