# Generated by Django 4.1 on 2022-09-25 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_alter_smart_phone_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartphoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Smart_phoneinfo',
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 11, 0, 59, 872452)),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 11, 0, 59, 872452)),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 11, 0, 59, 872452)),
        ),
        migrations.AddField(
            model_name='smartphoneinfo',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.smart_phone'),
        ),
    ]
