# Generated by Django 4.1 on 2022-08-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_alter_smart_watch_brand_alter_smart_watch_watch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart_phone',
            old_name='avalablity',
            new_name='availablity',
        ),
        migrations.RenameField(
            model_name='smart_watch',
            old_name='avalablity',
            new_name='availablity',
        ),
        migrations.RenameField(
            model_name='tabs',
            old_name='avalablity',
            new_name='availablity',
        ),
    ]
