# Generated by Django 4.1 on 2022-08-25 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_rename_avalablity_smart_phone_availablity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='storage',
            field=models.IntegerField(default=128, validators=[django.core.validators.MaxValueValidator(512), django.core.validators.MinValueValidator(128)]),
        ),
    ]
