# Generated by Django 4.1 on 2022-08-25 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_alter_smart_phone_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabs',
            name='storage',
            field=models.IntegerField(default=128, validators=[django.core.validators.MaxValueValidator(128), django.core.validators.MinValueValidator(1024)]),
        ),
    ]
