# Generated by Django 4.1 on 2022-09-25 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_alter_smart_phone_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphoneinfo',
            name='display_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='smartphoneinfo',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 11, 5, 20, 932774)),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 11, 5, 20, 932774)),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 11, 5, 20, 932774)),
        ),
    ]
