# Generated by Django 4.1 on 2022-09-28 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_alter_smart_phone_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartwatchinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='smart_phone',
            name='ram',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='tabs',
            name='ram',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 14, 56, 48, 752710)),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 14, 56, 48, 752710)),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 14, 56, 48, 752710)),
        ),
        migrations.DeleteModel(
            name='SmartphoneInfo',
        ),
        migrations.DeleteModel(
            name='SmartwatchInfo',
        ),
    ]
