# Generated by Django 4.1 on 2022-08-26 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_smart_phone_price_smart_watch_price_tabs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='storage',
            field=models.IntegerField(default=128, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(1024)]),
        ),
    ]
