# Generated by Django 4.1 on 2022-09-30 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_remove_smartwatchinfo_info_smart_phone_ram_tabs_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 14, 21, 53, 262420)),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 14, 21, 53, 262420)),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 14, 21, 53, 263420)),
        ),
    ]
