# Generated by Django 4.1 on 2022-10-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_alter_smart_phone_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart_watch',
            old_name='instock_count',
            new_name='instock',
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 0, 52, 13, 655951)),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 0, 52, 13, 655951)),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 0, 52, 13, 655951)),
        ),
    ]
