# Generated by Django 4.1 on 2022-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_alter_tabs_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_phone',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tabs',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
