# Generated by Django 4.1 on 2022-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_smart_phone_description_smart_watch_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
