# Generated by Django 4.1 on 2022-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_alter_smart_phone_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_watch',
            name='watch_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
