# Generated by Django 4.1 on 2022-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_alter_smart_watch_watch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_watch',
            name='brand',
            field=models.CharField(max_length=20),
        ),
    ]
