# Generated by Django 4.1 on 2022-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_alter_smart_watch_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart_phone',
            old_name='phone_colour',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='smart_phone',
            old_name='phone_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='smart_phone',
            old_name='instock_count',
            new_name='instock',
        ),
        migrations.RenameField(
            model_name='smart_phone',
            old_name='phone_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='smart_watch',
            old_name='watch_colour',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='smart_watch',
            old_name='watch_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='smart_watch',
            old_name='watch_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tabs',
            old_name='tablet_colour',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='tabs',
            old_name='tablet_images',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='tabs',
            name='instock_count',
        ),
        migrations.AddField(
            model_name='tabs',
            name='instock',
            field=models.IntegerField(null=True),
        ),
    ]
