# Generated by Django 4.1 on 2022-09-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_rename_phone_colour_smart_phone_colour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabs',
            old_name='tab_name',
            new_name='name',
        ),
    ]
