# Generated by Django 3.2.14 on 2022-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0025_rename_tab_name_tabs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_phone',
            name='phone_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
