# Generated by Django 3.2.14 on 2022-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0027_auto_20220902_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabs',
            name='tab_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='watch_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
