# Generated by Django 3.2.14 on 2022-09-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_auto_20220902_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='tab_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(default=2, null=True)),
                ('specificatios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.smart_phone')),
            ],
        ),
    ]
