# Generated by Django 3.2.14 on 2022-09-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0029_auto_20220902_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='phoneinfo',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='phoneinfo',
            name='specificatios',
        ),
        migrations.AddField(
            model_name='phoneinfo',
            name='phone_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapp.smart_phone'),
        ),
    ]
