# Generated by Django 4.1 on 2022-09-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0031_phoneinfo_display_phoneinfo_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinfo',
            name='phone_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapp.smart_phone'),
        ),
    ]
