# Generated by Django 4.1 on 2022-09-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0032_alter_phoneinfo_phone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabInfo',
            fields=[
                ('tabinfo', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapp.tabs')),
                ('ram', models.IntegerField(blank=True, default=8)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='WatchInfo',
            fields=[
                ('watchinfo', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapp.smart_watch')),
                ('wacth_os', models.CharField(max_length=15, null=True)),
                ('watch_reviews', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='phoneinfo',
            old_name='phone_id',
            new_name='phoneinfo',
        ),
        migrations.AddField(
            model_name='phoneinfo',
            name='operating_os',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='phoneinfo',
            name='phone_reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='ram',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
