# Generated by Django 3.2.14 on 2022-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0033_tabinfo_watchinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
