# Generated by Django 3.2.14 on 2022-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0034_alter_tabs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='images',
            field=models.FileField(upload_to='tablet_image'),
        ),
    ]
