# Generated by Django 3.2.14 on 2022-09-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0035_alter_tabs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabinfo',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tabinfo',
            name='tabinfo',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapp.tabs'),
        ),
    ]
