# Generated by Django 4.1.1 on 2022-09-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0037_tabinfo_id_alter_tabinfo_tabinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='name',
            field=models.CharField(max_length=50, verbose_name=str),
        ),
        migrations.AlterField(
            model_name='tabinfo',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tabinfo',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tabinfo',
            name='tabinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.tabs'),
        ),
    ]
