# Generated by Django 4.1.1 on 2022-09-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0039_alter_tabs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
