# Generated by Django 4.1.1 on 2022-09-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0040_alter_smart_phone_name_alter_tabs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabinfo',
            name='tabinfo',
        ),
        migrations.RemoveField(
            model_name='watchinfo',
            name='watchinfo',
        ),
        migrations.DeleteModel(
            name='PhoneInfo',
        ),
        migrations.DeleteModel(
            name='TabInfo',
        ),
        migrations.DeleteModel(
            name='WatchInfo',
        ),
    ]
