# Generated by Django 4.1.1 on 2022-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0042_smart_phone_camera_smart_phone_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smart_phone',
            name='phone_id',
        ),
        migrations.RemoveField(
            model_name='smart_watch',
            name='watch_id',
        ),
        migrations.RemoveField(
            model_name='tabs',
            name='tab_id',
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
