# Generated by Django 4.1.1 on 2022-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0043_remove_smart_phone_phone_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_phone',
            name='phone_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='smart_watch',
            name='watch_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tabs',
            name='tab_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smart_phone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
