# Generated by Django 4.1 on 2022-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0044_smart_phone_phone_id_smart_watch_watch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_phone',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='smart_watch',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
