# Generated by Django 4.1 on 2022-10-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
    ]
