# Generated by Django 4.1 on 2022-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0026_alter_smart_phone_date_added_and_more'),
        ('customer_purchase', '0002_remove_cart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='coreapp.smart_phone'),
        ),
    ]
