# Generated by Django 4.1 on 2022-10-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0002_alter_cart_products_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.CharField(max_length=90000, null=True),
        ),
    ]
