# Generated by Django 4.1 on 2022-10-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0004_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='products_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartproducts', to='customer_purchase.cart'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='products',
            field=models.CharField(max_length=90000, null=True),
        ),
    ]
