# Generated by Django 4.1 on 2022-10-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0004_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
