# Generated by Django 4.1 on 2022-10-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0029_alter_smart_phone_date_added_and_more'),
        ('customer_purchase', '0005_remove_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_smartphones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.smart_phone'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products_tabs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.tabs'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products_watches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.smart_watch'),
        ),
    ]
