# Generated by Django 4.1 on 2022-10-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0006_alter_cartproducts_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_purchase.cart'),
        ),
    ]
