# Generated by Django 4.1 on 2022-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0007_rename_products_tabs_cart_product_tabs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_smartphones',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_tabs',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_watches',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.CharField(max_length=90000, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_cart_cost',
            field=models.IntegerField(null=True),
        ),
    ]
