# Generated by Django 4.1 on 2022-10-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0009_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
