# Generated by Django 4.1.1 on 2022-10-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_purchase', '0010_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_phone',
        ),
    ]
