# Generated by Django 4.1.1 on 2022-10-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_smart_phone_date_added_and_more'),
        ('customer_purchase', '0011_rename_product_orderitem_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_watch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.smart_watch'),
        ),
    ]
